apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
  - name: cm-test-app
    image: ghcr.io/tang-yin/frontend-redis-custom:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: serverxml
      mountPath: /configfiles
  volumes:
  - name: serverxml
    configMap:
      name: cm-appconfigfiles
      items:                       # 不使用items会依据key进行生成
      - key: key-serverxml
        path: server.xml
      - key: key-loggingproperties
        path: logging.properties
