apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-appconfigfiles
data:
  key-serverxml: |
    <?xml version='1.0' encoding='utf-8'?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
      <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
      <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
      <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
      <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
      <GlobalNamingResources>
        <Resource name="UserDatabase" auth="container" type="org.apache.catalina.UserDatabase" description="User database that can be updated and saved" factory="org.apache.catalina.users.MemoryUserDatabaseFactory" pathname="conf/tomcat-users.xml" />
      </GlobalNamingResources>

      <Service name="Catalina">
        <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Realm className="orh.apache.catalina.realm.LockOutRealm">
            <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase" />
          </Realm>
          <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
            <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" prefix="localhost_access_log." suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b" />
          </Host>
        </Engine>
      </Service>
    </Server>
  key-loggingproperties: |
    "handlers=1catalina.org.apache.juli.FileHandler, 2localhost.org.apache.juli.FileHandler, 3manager.org.apache.juli.FileHandler, 4host-manager.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler\r\n\r\n

    .handlers= 1catalina.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler\r\n\r\n

    1catalina.org.apache.juli.FileHandler.level= FINE
    1catalina.org.apache.juli.FileHandler.directory = $(catalina.base)/logs
    1catalina.org.apache.juli.FileHandler.prefix = catalina.

    2localhost.org.apache.juli.FileHandler.level= FINE
    2localhost.org.apache.juli.FileHandler.directory = $(catalina.base)/logs
    2localhost.org.apache.juli.FileHandler.prefix = localhost.

    3manager.org.apache.juli.FileHandler.level= FINE
    3manager.org.apache.juli.FileHandler.directory = $(catalina.base)/logs
    3manager.org.apache.juli.FileHandler.prefix = manager.

    4host-manager.org.apache.juli.FileHandler.level= FINE
    4host-manager.org.apache.juli.FileHandler.directory = $(catalina.base)/logs
    4host-manager.org.apache.juli.FileHandler.prefix = host-manager.

    java.util.logging.ConsoleHandler.level= FINE
    java.util.logging.ConsoleHandler.formatter= java.util.logging.SimpleFormatter

    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].level = INFO
    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].handlers = 2localhost.org.apache.juli.FileHandler

    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].level = INFO
    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].handlers = 3manager.org.apache.juli.FileHandler

    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].level = INFO
    org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].handlers = 4host-manager.org.apache.juli.FileHandler"
